package main

import (
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"strings"
	"time"

	"github.com/gorilla/feeds"
	"github.com/mmcdole/gofeed"
)

// OutputStanderd は、フィードを標準出力に出力します。
// フィルタリング済みか否かに応じて、表示を調整します。
func OutputStanderd(data interface{}) {
	if err := OutputStandardTo(os.Stdout, data, time.Now()); err != nil {
		log.Println(err)
	}
}

// OutputStandardTo writes the feed data as RSS to w using now for generated timestamps.
func OutputStandardTo(w io.Writer, data interface{}, now time.Time) error {
	outFeed, err := buildOutputFeed(data, now)
	if err != nil {
		return err
	}

	rss, err := outFeed.ToRss()
	if err != nil {
		return err
	}
	_, err = fmt.Fprint(w, rss)
	return err
}

func OutputAtomTo(w io.Writer, data interface{}, now time.Time) error {
	outFeed, err := buildOutputFeed(data, now)
	if err != nil {
		return err
	}

	atom, err := outFeed.ToAtom()
	if err != nil {
		return err
	}
	_, err = fmt.Fprint(w, atom)
	return err
}

func buildOutputFeed(data interface{}, now time.Time) (*feeds.Feed, error) {
	itemsToProcess, err := outputFeedItems(data)
	if err != nil {
		return nil, err
	}
	outFeed := &feeds.Feed{
		Title:       "feed2cli generated feed",
		Link:        &feeds.Link{Href: ""},
		Description: "A feed generated by feed2cli",
		Created:     now,
	}

	for _, v := range itemsToProcess {
		description := v.Description

		var newDescription strings.Builder
		newDescription.WriteString(v.Description)

		if v.HatenaBookmarkCount != "" && v.HatenaBookmarkCount != "0" {
			newDescription.WriteString(fmt.Sprintf("\n<p>Hatena Bookmark: <b>%s</b></p>", v.HatenaBookmarkCount))
		}

		if len(v.HatenaBookmarkComments) > 0 {
			newDescription.WriteString("\n<p><b>Comments:</b></p><ul>")
			for _, c := range v.HatenaBookmarkComments {
				if c.Comment != "" {
					newDescription.WriteString(fmt.Sprintf("<li>%s (%s): %s</li>", c.User, c.Timestamp, c.Comment))
				}
			}
			newDescription.WriteString("</ul>")
		}
		description = newDescription.String()

		created := now
		if published, ok := v.PublishedTime(); ok {
			created = published
		}

		item := &feeds.Item{
			Title:       v.Title,
			Link:        &feeds.Link{Href: v.URL},
			Description: description,
			Created:     created,
		}
		if v.ID != "" {
			item.Id = v.ID
		}
		outFeed.Add(item)
	}

	return outFeed, nil
}

func outputFeedItems(data interface{}) ([]FeedItem, error) {
	switch data.(type) {
	case []FeedItem, []FeedDocument, []*FilteredItem, []*gofeed.Feed, []*gofeed.Item:
		return FeedItemsFromData(data), nil
	default:
		return nil, errors.New("サポートされていないデータ型です")
	}
}
